config_version = 13

[backdrop]
enabled = true

[bar]
order = [ "Top" ]

    [bar.Top]
    background_opacity = 0.67999998480081558
    border = "primary"
    center = [ "notifications", "todo", "media", "power_profile", "group:g3", "wallhaven", "caffeine" ]
    end = [
        "network",
        "group:g2",
        "bluetooth",
        "widget",
        "tray",
        "notes",
        "clipboard",
        "volume",
        "brightness",
        "battery",
        "session"
    ]
    margin_ends = 0
    padding = 6
    radius = 20
    radius_top_left = 0
    radius_top_right = 0
    shadow = false
    start = [ "launcher", "taskbar", "group:g1", "summary" ]
    thickness = 30

        [[bar.Top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "cpu", "ram", "temp" ]
        opacity = 1.0
        padding = 6.0

        [[bar.Top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "network_rx", "network_tx" ]
        opacity = 1.0
        padding = 6.0

        [[bar.Top.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "clock", "date" ]
        opacity = 1.0
        padding = 6.0
        radius = 12.0

[calendar]
enabled = true
refresh_minutes = 60

    [calendar.account.personal_google]
    color = "primary"
    name = "Chirayu"
    type = "google"

[control_center]
sidebar = "full"
sidebar_section = "full"
width = 800

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "dark_mode"

[dock]
background_opacity = 0.79999998211860657
icon_size = 39
inactive_opacity = 0.79999998211860657
launcher_icon = "layout-grid"
launcher_position = "start"
pinned = [ "zen", "files", "kitty", "dev.zed.Zed", "codium", "org.blender.Blender", "org.freecad.FreeCAD", "vesktop", "steam" ]
radius = 15
reserve_space = false
shadow = false
show_dots = true
smart_auto_hide = true

[hooks]
battery_charging = "~/Fedora-noct/hypr/Scripts/charging.sh"
battery_discharging = "~/Fedora-noct/hypr/Scripts/discharging.sh"
started = "rfkill block bluetooth"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 600.0

[location]
address = "dadar east, india"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 1081.0
    output = "eDP-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.79999998211860657

[osd]
background_opacity = 0.79999998211860657

[plugin_settings."gustav0ar/drive-health"]
system_collector_enabled = true

[plugin_settings."noctalia/notes"]
panel_open_near_click = true
panel_placement = "attached"
panel_position = "auto"

[plugin_settings."noctalia/wallhaven"]
api_key = ""
browser_open_near_click = true
download_dir = "~/Pictures/Wallpapers"

[plugins]
enabled = [ "noctalia/wallhaven", "noctalia/timer", "nightwatch75/todo", "noctalia/notes" ]

[shell]
avatar_path = "/home/thatmechguy/Downloads/0a398a0299f1ea314f8288d160655bba.png"
password_style = "random"
polkit_agent = true
screen_time_enabled = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    categories = false
    compact = true
    sort_by_usage = false

    [shell.panel]
    clipboard_placement = "attached"
    clipboard_position = "auto"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_launcher = true
    polkit_placement = "attached"
    polkit_position = "auto"
    session_placement = "floating"
    shadow = false
    transparency_mode = "soft"

    [shell.screen_corners]
    size = 15

    [shell.screenshot]
    directory = "~/Pictures/Screenshots"

    [shell.shadow]
    direction = "center"

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "soft"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "foot", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [
        "pywalfox",
        "zen-browser",
        "discord",
        "libreoffice",
        "neovim",
        "obsidian",
        "vscode",
        "zed",
        "steam",
        "obs",
        "papirus-icons"
    ]

[wallpaper.default]
path = "/home/chirayu/Pictures/Wallpapers/wallhaven-d8kyjj.png"

[wallpaper.last]
path = "/home/chirayu/Pictures/Wallpapers/wallhaven-d8kyjj.png"

[wallpaper.monitors.eDP-1]
path = "/home/chirayu/Pictures/Wallpapers/wallhaven-d8kyjj.png"

[widget.cpu]
display = "text"
visualization = "none"

[widget.launcher]
glyph = "layout-grid"

[widget.media]
max_length = 104
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.network_rx]
display = "text"
visualization = "none"

[widget.network_tx]
display = "text"
visualization = "none"

[widget.notes]
type = "noctalia/notes:notes"

[widget.ram]
display = "text"
visualization = "none"

[widget.summary]
type = "gustav0ar/drive-health:summary"

[widget.taskbar]
capsule = true
capsule_radius = "auto"
empty_color = "surface"
group_by_workspace = true
occupied_color = "on_hover"
workspace_label_placement = "inside"

[widget.temp]
display = "text"
visualization = "none"

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.volume.actions]
scroll_down = "volume-down 1%"
scroll_up = "volume-up 1%"

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.widget]
type = "yuuto/arch-updater:widget"

[widget.workspaces]
labels_only_when_occupied = true